export const defaultProducts = [
  {
    id: 1,
    name: "CLASSIC CLEAN SHAMPOO",
    brand: "CALIFORNIA NATURALS",
    desc: "Зөөлөн цэвэрлэж, тэжээл өгнө",
    price: 47960,
    oldPrice: 59950,
    discount: 20,
    category: "hair",
    badge: "hot",
    image: "/products/classic-shampoo-front.png",
    hoverImage: "/products/classic-shampoo-hover.png",
    rating: 4.6,
    reviews: 76,
    fullDesc: 'Кокосын тос болон байгалийн гаралтай орцуудаар баяжуулсан Classic Clean шампунь нь бүх төрлийн үсэнд тохирох өдөр тутмын цэвэрлэгч юм. Хатуу химийн бодисгүйгээр үсийг зөөлнөөр цэвэрлэж, тэжээл өгнө.',
    ingredients: 'Кокосын тос, алоэ вера, витамин E, камелийн тос. Сульфат, парабен, силикон агуулаагүй. 99% байгалийн гаралтай.',
    howToUse: 'Чийгтэй үсэнд хэрэглэнэ. Зохих хэмжээг авч үсэн дээр жигд түрхэж, хуруугаараа зөөлнөөр массаж хийнэ. Дараа нь сайтар зайлна.'
  },
  {
    id: 2,
    name: "SUPER MOISTURE SHAMPOO",
    brand: "CALIFORNIA NATURALS",
    desc: "Хуурай үсийг гүн чийгшүүлнэ",
    price: 47960,
    oldPrice: null,
    discount: 0,
    category: "hair",
    badge: "new",
    image: "/products/super-moisture-shampoo.png",
    hoverImage: "/products/super-moisture-shampoo-hover.png",
    rating: 4.5,
    reviews: 114,
    fullDesc: 'Super Moisture шампунь нь хуурай, гэмтсэн үсэнд гүн чийгшүүлэлт өгнө. Байгалийн тос, витаминуудаар баяжуулсан найрлага нь үсийг зөөлөн, уян хатан болгоно.',
    ingredients: 'Ши тос, жожоба тос, кокосын тос, алоэ вера, витамин B5, E. Сульфат, парабен, силикон агуулаагүй.',
    howToUse: 'Чийгтэй үсэнд зохих хэмжээг авч, хөөсрүүлж массаж хийнэ. 1-2 минут үлдээгээд сайтар зайлна.'
  },
  {
    id: 3,
    name: "RE:GRO ANTI-THINNING SHAMPOO",
    brand: "CALIFORNIA NATURALS",
    desc: "Үсний ургалтыг дэмжинэ",
    price: 47960,
    oldPrice: 59950,
    discount: 20,
    category: "hair",
    badge: "sale",
    image: "/products/regro-shampoo.png",
    hoverImage: "/products/regro-shampoo-hover.jpg",
    rating: 4.5,
    reviews: 55,
    fullDesc: 'Капиксил, кофеин, биотин, розмаринаар баяжуулсан Re:GRO шампунь нь үсний ургалтыг дэмжиж, нимгэрч буй үсийг бэхжүүлнэ. Эмнэлзүйн туршилтаар баталгаажсан.',
    ingredients: '5% Капиксил®, кофеин, биотин, розмарин, тарвас, биднийн тос. Сульфат, парабен, силикон агуулаагүй. 98% байгалийн гаралтай.',
    howToUse: 'Чийгтэй үсэнд хэрэглэж, 2-3 минут зөөлнөөр массаж хийнэ. Хамгийн сайн үр дүнд Re:GRO кондиционертой хамт хэрэглэнэ.'
  },
  {
    id: 4,
    name: "SUPER MOISTURE CONDITIONER",
    brand: "CALIFORNIA NATURALS",
    desc: "Хуурай үсийг зөөлрүүлнэ",
    price: 47960,
    oldPrice: null,
    discount: 0,
    category: "hair",
    badge: "hot",
    image: "/products/super-moisture-conditioner.png",
    hoverImage: "/products/super-moisture-conditioner-hover.png",
    rating: 4.5,
    reviews: 114,
    fullDesc: 'Хуурай, эвдэрсэн үсийг гүнзгий чийгшүүлж, зөөлрүүлэхэд зориулсан кондиционер. Үсний уян хатан чанарыг сэргээж, гялалзуулна.',
    ingredients: 'Арганы тос, ши тос, витамин B5, жожоба тос. Сульфат, парабен, силикон агуулаагүй.',
    howToUse: 'Шампуньдсаны дараа чийгтэй үсэнд түрхэж, 1-3 минут хүлээгээд угаана. Үсний үзүүрт илүү анхаарал хандуулна.'
  },
  {
    id: 5,
    name: "CLASSIC CLEAN CONDITIONER",
    brand: "CALIFORNIA NATURALS",
    desc: "Бүх төрлийн үсэнд тохирно",
    price: 47960,
    oldPrice: 59950,
    discount: 20,
    category: "hair",
    badge: "sale",
    image: "/products/classic-clean-shampoo-mini.png",
    hoverImage: "/products/classic-conditioner-hover.png",
    rating: 4.8,
    reviews: 68,
    fullDesc: 'Кокосын тосоор баяжуулсан Classic Clean кондиционер нь бүх төрлийн үсийг зөөлрүүлж, чийгшүүлж, удирдахад хялбар болгоно.',
    ingredients: 'Кокосын тос, алоэ вера, витамин E, камелийн тос. Сульфат, парабен, силикон агуулаагүй. 99% байгалийн гаралтай.',
    howToUse: 'Шампуньдсаны дараа чийгтэй үсний үзүүрт түрхэж, 1-2 минут хүлээгээд угаана.'
  },
  {
    id: 6,
    name: "LEAVE-IN CONDITIONER & DETANGLER",
    brand: "CALIFORNIA NATURALS",
    desc: "Гялалзуулж, зангилаа задлана",
    price: 47960,
    oldPrice: null,
    discount: 0,
    category: "hair",
    badge: "new",
    image: "/products/leave-in-conditioner.png",
    hoverImage: "/products/leave-in-conditioner-hover.jpg",
    rating: 4.8,
    reviews: 41,
    fullDesc: 'Угаахгүй кондиционер нь хуурай, зангилаатай, буржигнасан үсийг зөөлрүүлж, гялалзуулна. Хөнгөн жинтэй, дарамтгүй чийгшүүлэлт.',
    ingredients: 'Алоэ вера, кокосын тос, камомил, арганы тос. Сульфат, парабен, силикон агуулаагүй.',
    howToUse: 'Угаасны дараа алчуураар хатааж, зохих хэмжээг үсний дунд хэсэг ба үзүүрт жигд түрхэнэ. Угаахгүй.'
  },
  {
    id: 7,
    name: "DEEP REPAIR HAIR MASK",
    brand: "CALIFORNIA NATURALS",
    desc: "Хуурай үсний эмчилгээ",
    price: 47960,
    oldPrice: 59950,
    discount: 20,
    category: "hair",
    badge: "sale",
    image: "/products/super-moisture-texture.png",
    hoverImage: "/products/deep-repair-mask-hover.jpg",
    rating: 4.7,
    reviews: 58,
    fullDesc: 'Хуурай, эвдэрсэн үсний хамгийн сайн эмчилгээ. Гүн тэжээлийн маск нь үсийг дотроос нь сэргээж, уян хатан чанарыг нэмэгдүүлнэ.',
    ingredients: 'Ши тос, арганы тос, кератин, витамин E, кокосын тос. Сульфат, парабен, силикон агуулаагүй.',
    howToUse: 'Угаасны дараа чийгтэй үсэнд жигд түрхэж, 5-10 минут хүлээнэ. Сайтар зайлна. Долоо хоногт 1-2 удаа хэрэглэнэ.'
  },
  {
    id: 8,
    name: "GLOW OIL BODY WASH",
    brand: "CALIFORNIA NATURALS",
    desc: "Арьсыг зөөлрүүлж гялалзуулна",
    price: 47960,
    oldPrice: null,
    discount: 0,
    category: "body",
    badge: "hot",
    image: "/products/glow-oil-bodywash.png",
    hoverImage: "/products/glow-oil-bodywash-hover.jpg",
    rating: 4.8,
    reviews: 23,
    fullDesc: 'Алтан тосон бие угаалга нь арьсыг зөөлрүүлж, гялалзуулна. Нарийн цитрус үнэрээр нарийхан тос болон витаминаар арьсыг тэжээнэ.',
    ingredients: 'Жожоба тос, витамин E, апельсины тос, камелийн тос. Сульфат, парабен агуулаагүй.',
    howToUse: 'Чийгтэй арьсан дээр зохих хэмжээг авч хөөсрүүлнэ. Сайтар зайлна.'
  },
  {
    id: 9,
    name: "GLOW OIL ТЭЖЭЭЛИЙН ТОС",
    brand: "CALIFORNIA NATURALS",
    desc: "Арьс ба үсний гүн тэжээл",
    price: 67960,
    oldPrice: 84950,
    discount: 20,
    category: "body",
    badge: "sale",
    image: "/products/glow-oil-front.png",
    hoverImage: "/products/glow-oil-hover.png",
    rating: 4.6,
    reviews: 34,
    fullDesc: 'Арьс болон үсний гүн тэжээлд зориулсан тос. Хөнгөн жинтэй, хурдан шимдэг, арьсыг зөөлрүүлж гялалзуулна.',
    ingredients: 'Жожоба тос, арганы тос, розмарин, сандалын тос. Сульфат, парабен, силикон агуулаагүй.',
    howToUse: 'Хуурай эсвэл чийгтэй арьс/үсэн дээр хэдэн дусал дусааж, зөөлнөөр түрхэнэ.'
  },
  {
    id: 10,
    name: "CLASSIC CLEAN ШАМПУНЬ + КОНДИЦИОНЕР",
    brand: "CALIFORNIA NATURALS",
    desc: "Өдөр тутмын арчилгааны багц",
    price: 89900,
    oldPrice: 119900,
    discount: 25,
    category: "set",
    badge: "hot",
    image: "/products/classic-clean-shampoo.png",
    hoverImage: "/products/classic-shampoo-hover.png",
    rating: 4.8,
    reviews: 117,
    fullDesc: 'Шампунь + кондиционер хосолсон багц нь өдөр тутмын арчилгаанд тохиромжтой. Кокосын тосоор баяжуулсан, бүх төрлийн үсэнд тохирно.',
    ingredients: 'Кокосын тос, алоэ вера, витамин E, камелийн тос. Сульфат, парабен, силикон агуулаагүй. 99% байгалийн гаралтай.',
    howToUse: 'Шампуньг чийгтэй үсэнд түрхэж, массаж хийгээд угаана. Кондиционерийг үсний үзүүрт 1-2 минут түрхээд угаана.'
  },
  {
    id: 11,
    name: "SUPER MOISTURE ШАМПУНЬ + КОНДИЦИОНЕР",
    brand: "CALIFORNIA NATURALS",
    desc: "Гүн чийгшүүлэх багц",
    price: 89900,
    oldPrice: 119900,
    discount: 25,
    category: "set",
    badge: "sale",
    image: "/products/super-moisture-shampoo.png",
    hoverImage: "/products/super-moisture-shampoo-hover.png",
    rating: 4.5,
    reviews: 114,
    fullDesc: 'Super Moisture шампунь + кондиционер хосолсон багц нь хуурай, гэмтсэн үсэнд гүн чийгшүүлэлт өгнө. Ши тос, жожоба тосоор баяжуулсан.',
    ingredients: 'Ши тос, жожоба тос, кокосын тос, алоэ вера, витамин B5, E. Сульфат, парабен, силикон агуулаагүй. 99% байгалийн гаралтай.',
    howToUse: 'Шампуньг чийгтэй үсэнд түрхэж массаж хийнэ. Зайлсны дараа кондиционерийг үсний үзүүрт түрхэж 2-3 минут үлдээгээд угаана.'
  }
];

export const categoryNames = {
  hair: 'Үс арчилгаа',
  body: 'Бие арчилгаа',
  lip: 'Уруул',
  set: 'Багц'
};

export function formatPrice(price) {
  return price.toLocaleString('mn-MN') + '₮';
}
